[functions.createProfile]
verify_jwt = false

[functions.process-payment]
verify_jwt = false

[functions.enroll-student]
verify_jwt = false

[functions.manage-user]
verify_jwt = false

[functions.webhook-stripe]
verify_jwt = false

[functions.sync-school]
verify_jwt = false

[functions.upload-student-document]
verify_jwt = false
